version: 2.1
jobs:
  install:
    working_directory: ~/renovate-config
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder .cache/yarn
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .cache/yarn
            - node_modules
      - persist_to_workspace:
          root: ~/renovate-config
          paths:
            - .cache/yarn
            - node_modules
  test:
    working_directory: ~/renovate-config
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/renovate-config
      - run:
          name: test
          command: yarn test

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install

