version: 2.1
jobs:
  install:
    working_directory: ~/renovate-config
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/renovate-config
          paths:
            - ./node_modules
  test:
    working_directory: ~/renovate-config
    docker:
      - image: circleci/node:17.2.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/renovate-config
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install

